from __future__ import annotations

# Shared defaults and thresholds across CLI and batch.
DEFAULT_VOICE = "af_bella"
DEFAULT_LANG = "en-us"
DEFAULT_SPEED = 0.9
DEFAULT_MAX_CHARS = 850
DEFAULT_MAX_PHONEME_CHARS = 450
DEFAULT_SILENCE_MS = 250
DEFAULT_MAX_PART_MINUTES = 30.0
DEFAULT_HEARTBEAT_SECONDS = 30.0
DEFAULT_OUTPUT_DIR = ".\\out"
DEFAULT_TRIM_MODE = "off"
DEFAULT_WORKER_SILENCE_TIMEOUT_SECONDS = 300.0
DEFAULT_BOOTSTRAP_SILENCE_TIMEOUT_SECONDS = 90.0
MODEL_URL = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.onnx"
VOICES_URL = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin"
GROUP_PATH_SEPARATOR = " / "
DEFAULT_CPU_MAX_CHARS = 12000
DEFAULT_CPU_WORKER_MAX_CHARS = 900
DEFAULT_GPU_LARGE_CHAPTER_MAX_CHARS = 950
DEFAULT_GPU_SMALL_CHAPTER_MAX_CHARS = 1350
DEFAULT_GPU_LARGE_CHAPTER_MIN_CHARS = 450
DEFAULT_GPU_LARGE_CHAPTER_ESTIMATED_CHUNKS = 12
DEFAULT_GPU_WORKERS = 2
DEFAULT_CPU_WORKERS = 1
DEFAULT_MAX_RETRIES = 2
DEFAULT_GPU_RECOVERY_SECONDS = 12.0
DEFAULT_AGGRESSIVE_GPU_RECOVERY = False
DEFAULT_SERIALIZE_GPU_BOOTSTRAP = True
DEFAULT_MAX_PARTS_PER_RUN = 0
DEFAULT_NO_CONSOLE_CONTROLS = False
DEFAULT_DEBUG = False
DEFAULT_MD_SINGLE_CHAPTER = False
DEFAULT_MAX_CHAPTER_CHARS = 0
DEFAULT_WARMUP_TEXT = "Warmup run."
DEFAULT_MP3_ONLY = True
DEFAULT_FORCE = False
DEFAULT_FRESH = False
DEFAULT_KEEP_CHUNKS = False
DEFAULT_LIST_CHAPTERS = False
DEFAULT_CHAPTER_INDEX = None
DEFAULT_CHAPTER_CACHE = None
DEFAULT_OUTPUT_SUBDIR = None
DEFAULT_OUTPUT_NAME = None
DEFAULT_TEMP_DIR = None
DEFAULT_PROVIDERS = None
DEFAULT_PROVIDER_PRIORITY = [
    "CUDAExecutionProvider",
    "DmlExecutionProvider",
    "ROCMExecutionProvider",
    "CPUExecutionProvider",
]
WORKER_PROGRESS_INTERVAL_SECONDS = 3.0
WORKER_WAIT_LOG_INTERVAL_SECONDS = 15.0
CPU_IDLE_STEP_SECONDS = 120.0
DEFAULT_WORKER_SILENCE_TIMEOUT_SECONDS = 300.0
DEFAULT_BOOTSTRAP_SILENCE_TIMEOUT_SECONDS = 90.0
SHORT_SECTION_KEYWORDS = (
    "title page",
    "table of contents",
    "copyright",
    "acknowledg",
    "dedication",
    "map",
    "maps",
    "cover",
    "foreword",
    "afterword",
    "synopsis",
    "about the author",
    "about the publisher",
)
